# This workflow deploys a TakeShape project.
# Make sure to set Secrets in your GitHub repo's settings!
# https://github.com/<profile>/<repo>/settings/secrets 

name: Deploy to TakeShape
description: Deploy a project using the TakeShape SSG
branding:
  color: purple
  icon: arrow-up

# We only want to deploy on changes to the master branch
# You can change this to better meet the needs of your own project
# For example, you could deploy to different static sites depending on the branch
# Learn more about configuring jobs:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs commands using the runners shell
    # Uses secrets set in https://github.com/<profile>/<repo>/settings/secrets
    # You can change this to better meet the needs of your own project
    # For example, if you use Yarn instead of npm, you should change the command
    - name: Install Dependencies and Deploy
      run: |
        npm install
        npm run deploy
      env:
        TS_PROJECT_ID: ${{ secrets.TS_PROJECT_ID }}
        TS_AUTH_TOKEN: ${{ secrets.TS_AUTH_TOKEN }}
        TS_SITE_NAME: ${{ secrets.TS_SITE_NAME }} 
        TS_SITE_ID: ${{ secrets.TS_SITE_ID }}       
        
