name: Deploy to TakeShape
description: Deploy a project using the TakeShape SSG
branding:
  color: purple
  icon: arrow-up

inputs:
  project-id:
    description: "The ID of your TakeShape project. Found in the URL of your project on app.takeshape.io"
    required: true
  auth-token:
    description: "A TakeShape API key. [Learn how to create one](https://www.takeshape.io/docs/creating-an-api-key/) in the TakeShape docs"
    required: true
  site-name:
    description: "The name of the static site associated with your TakeShape project at app.takeshape.io/projects/<project-id>/sites"
    required: true
  site-id:
    description: "The ID of the static site you want to deploy. Found in the URL of the static site in your project on app.takeshape.io"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-id }}
    - ${{ inputs.auth-token }}
    - ${{ inputs.site-name }}
    - ${{ inputs.site-id }}        
